# Generated by Django 2.1.5 on 2019-04-14 07:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inContactList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('related_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chatsDB.Contacts')),
            ],
            options={
                'verbose_name': 'messages',
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatsDB.Messages'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
