# Generated by Django 2.1.5 on 2019-04-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='related_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatsDB.Contacts'),
        ),
    ]
