# Generated by Django 2.1.5 on 2019-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0005_auto_20190324_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='undelivered_messages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
