# Generated by Django 2.1.5 on 2019-03-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0006_auto_20190324_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='undelivered_messages',
        ),
    ]
