# Generated by Django 2.1.5 on 2019-03-24 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0007_remove_contacts_undelivered_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inContactList', to=settings.AUTH_USER_MODEL),
        ),
    ]
