# Generated by Django 2.1.5 on 2019-03-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0010_auto_20190325_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='last_message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='chatsDB.Messages'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
