# Generated by Django 2.1.5 on 2019-03-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0011_auto_20190325_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chatsDB.Messages'),
        ),
    ]
