# Generated by Django 2.1.5 on 2019-03-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0012_auto_20190325_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='receiver',
            new_name='related_contact',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
    ]
