# Generated by Django 2.1.5 on 2019-03-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsDB', '0013_auto_20190325_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'messages'},
        ),
    ]
