# Generated by Django 2.1.5 on 2019-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190318_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='no description', max_length=100),
        ),
    ]
